### ISSUE TITLE
In same case xxtea fail

### ISSUE THREAD

**Issue by dataino-it** [alessandro1105/XXTEA_Arduino_Library#1]
# include <XXTEA.h>

void setup() {

  Serial.begin(9600);

  XXTEA xxtea("6b65ab3ec40de908");

  // Working
  //char\* s  = "38425;0;0;*E466D";
  //xxtea.encrypt(s);
  //xxtea.decrypt(s);
  //Serial.println(s);

  // NOT Working
  char\* s  = "38425;0;0;*E9DB7";
  xxtea.encrypt(s);
  xxtea.decrypt(s);
  Serial.println(s);

}

void loop() {}

**Comment by ofthesea-io** [comment]
I have noticed this too. Certain string lengths and certain combination of chars cause it to fall over

**Comment by dataino-it** [comment]
i solved by normalize the length to 16 adding chars at the end of msg

        int len = HEADER_SIZE + msgSize;
        
        uint8_t pad = 0;
        char padString[16];

        if ( encryptDecrypt ) {
          for ( i = 0 ; i <= 16 ; i++ ) { padString[i] = 0; }
            for ( i = len ; i < MAX_DATA ; i++ ) {
              if ( i == 16 || i == 32 || i == 48 || i == 64 || i == 80 || i ==96 || i == 112 || i == 128 ) {
                padString[ i - len ] = '\0';
              break;
            }
            
            padString[ i - len  ] = '=';
            
            pad++;
          }
        }

**Comment by ofthesea-io** [comment]
Thanks for the heads up. I will give that a try.
